"""ids/models.py — Shared data models for the Network IDS.

Defines enums, dataclasses, and helper functions used across all components.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class AttackType(str, Enum):
    """Recognised attack categories produced by the Detection_Engine."""

    PORT_SCAN = "PORT_SCAN"
    BRUTE_FORCE = "BRUTE_FORCE"
    DOS = "DOS"


class Severity(str, Enum):
    """Severity levels assigned to each Alert."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


@dataclass
class Alert:
    """A structured record of a single detected attack event.

    Fields
    ------
    id          UUID4 string, assigned by Alert_Manager before persistence.
    timestamp   ISO 8601 UTC string, e.g. "2024-01-15T10:30:00.123456Z".
    src_ip      IPv4 or IPv6 address string of the attacking host.
    attack_type One of the AttackType enum values.
    severity    One of the Severity enum values.
    metadata    Attack-specific fields (port_count, attempt_count, packet_rate, …).
    """

    id: str
    timestamp: str
    src_ip: str
    attack_type: AttackType
    severity: Severity
    metadata: dict = field(default_factory=dict)


@dataclass
class SuspiciousIP:
    """Aggregate record for a source IP that has triggered one or more alerts.

    Fields
    ------
    ip_address  IPv4 or IPv6 address string.
    first_seen  ISO 8601 UTC timestamp of the earliest alert from this IP.
    last_seen   ISO 8601 UTC timestamp of the most recent alert from this IP.
    alert_count Total number of alerts generated by this IP.
    attack_types List of distinct AttackType values seen from this IP.
    """

    ip_address: str
    first_seen: str
    last_seen: str
    alert_count: int
    attack_types: list[AttackType] = field(default_factory=list)


def severity_for_alert(attack_type: AttackType, **kwargs) -> Severity:
    """Return the appropriate Severity for an alert based on attack type and metadata.

    Severity mapping (from design document):

    PORT_SCAN
        port_count < 50  → MEDIUM
        port_count >= 50 → HIGH

    BRUTE_FORCE
        attempt_count < 50  → HIGH
        attempt_count >= 50 → CRITICAL

    DOS
        packet_rate < 500  → HIGH
        packet_rate >= 500 → CRITICAL

    Parameters
    ----------
    attack_type:
        The type of attack being classified.
    **kwargs:
        Attack-specific metadata values used to determine severity:
        - ``port_count`` (int)    — required for PORT_SCAN
        - ``attempt_count`` (int) — required for BRUTE_FORCE
        - ``packet_rate`` (float) — required for DOS

    Returns
    -------
    Severity
        The computed severity level.

    Raises
    ------
    ValueError
        If the attack_type is unrecognised.
    KeyError
        If a required metadata key is missing from kwargs.
    """
    if attack_type == AttackType.PORT_SCAN:
        port_count = kwargs["port_count"]
        return Severity.HIGH if port_count >= 50 else Severity.MEDIUM

    if attack_type == AttackType.BRUTE_FORCE:
        attempt_count = kwargs["attempt_count"]
        return Severity.CRITICAL if attempt_count >= 50 else Severity.HIGH

    if attack_type == AttackType.DOS:
        packet_rate = kwargs["packet_rate"]
        return Severity.CRITICAL if packet_rate >= 500 else Severity.HIGH

    raise ValueError(f"Unrecognised attack_type: {attack_type!r}")
